name: Private Server Builder

on:
  workflow_dispatch:
    inputs:
        appVersion:
          description: 'Private Server Version And Release Tag'
          required: true
          default: '1.X.X.X'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: ZIP File
        uses: vimtor/action-zip@v1
        with:
          files: PrivateSeverLauncher.bat
          recursive: false
          dest: PrivateServer.zip # will end up in working directory not the Publish folder

      - name: GIT Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Private Server v${{ github.event.inputs.appVersion }}"
          automatic_release_tag: ${{ github.event.inputs.appVersion }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: PrivateServer.zip
